/{page}/delete/{id}:
  get:
    description:
    reponses:
      200:

/:
  get:
    description:
    reponses:
      200:

/home:
  get:
    description:
    reponses:
      200:

/mentions:
  get:
    description:
    reponses:
      200:

/recent:
  get:
    description:
    reponses:
      200:

/hashtag/{ht}:
  get:
    description:
    reponses:
      200:

/followers:
  get:
    description:
    reponses:
      200:

/following:
  get:
    description:
    reponses:
      200:

/users:
  get:
    description:
    reponses:
      200:

/{name}:
  get:
    description:
    reponses:
      200:

/{name}/statuses/{id}:
  get:
    description:
    reponses:
      200:

/post:
  post:
    description:
    reponses:
      201:

/follow/{name}:
  post:
    description:
    reponses:
      201:

/unfollow/{name}:
  post:
    description:
    reponses:
      201:

/edit/{name}:
  get:
    description:
    reponses:
      200:

/edit:
  post:
    description:
    reponses:
      201:

/signup:
  get:
    description:
    reponses:
      200:

/login:
  get:
    description:
    reponses:
      200:
  post:
    description:
    reponses:
      201:

/logout:
  get:
    description:
    reponses:
      200:

/signup:
  post:
    description:
    reponses:
      201:

/static/{filename}:
  get:
    description:
    reponses:
      200: