'/:page/delete/:id'

'/'

'/home'

'/mentions'

'/recent'

'/hashtag/:ht'

'/followers'

'/following'

'/users'

'/:name'

'/:name/statuses/:id'

'/post',method='POST'

'/follow/:name',method='POST')

'/unfollow/:name',method='POST'

'/edit/:name', method='GET'

'/edit', method="POST"

'/signup'

'/login'

'/login', method='POST'

'/logout'

'/signup', method='POST'

'/static/:filename'